# @format

version: "3"

services:
    registro-visitas-api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: fpenaranda/registro_visitas_service:${TAG}
        restart: always
        ports:
            - "5000:80"
            - "5001:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:443;http://+:80
networks:
    default:
