// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPeConTI.Afiliaciones.RegistroAfiliaciones.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AfiliacionesContext))]
    [Migration("20230322190539_QuitarEstadosAfiliacion1")]
    partial class QuitarEstadosAfiliacion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Autorizacion.UsuarioAfiliados", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AfiliadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UsuarioAfiliados", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discapacitado")
                        .HasColumnType("bit");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<Guid>("EstadoCivilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EstadosAfiliacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<Guid>("NacionalidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentescoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioAfiliadosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("ParentescoId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TitularId");

                    b.HasIndex("UsuarioAfiliadosId");

                    b.ToTable("Afiliados", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosContactos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AfiliadosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CemapReferencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Laboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Particular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfiliadosId");

                    b.ToTable("AfiliadosContactos", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosDocumentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AfiliadosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DetalleDocumentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfiliadosId");

                    b.HasIndex("DocumentacionId");

                    b.ToTable("AfiliadosDocumentacion", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosDomicilios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AfiliadosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfiliadosId");

                    b.ToTable("AfiliadosDomicilios", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.DetalleDocumentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("DocumentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParentescoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentacionId");

                    b.HasIndex("PlanId");

                    b.ToTable("DetalleDocumentacion", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Documentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documentacion", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.EstadosCiviles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosCiviles", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Localidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProvinciasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciasId");

                    b.ToTable("Localidades", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Nacionalidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nacionalidades", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Parentescos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parentescos", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Planes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planes", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Provincias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.EstadosCiviles", "EstadoCivil")
                        .WithMany("Afiliados")
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Nacionalidades", "Nacionalidad")
                        .WithMany("Afiliados")
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Parentescos", "Parentesco")
                        .WithMany("Afiliados")
                        .HasForeignKey("ParentescoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Planes", "Plan")
                        .WithMany("Afiliados")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Afiliados")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Autorizacion.UsuarioAfiliados", null)
                        .WithMany("Afiliados")
                        .HasForeignKey("UsuarioAfiliadosId");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Parentesco");

                    b.Navigation("Plan");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosContactos", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", "Afiliado")
                        .WithMany()
                        .HasForeignKey("AfiliadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Afiliado");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosDocumentacion", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", "Afiliado")
                        .WithMany()
                        .HasForeignKey("AfiliadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Documentacion", "Documentacion")
                        .WithMany()
                        .HasForeignKey("DocumentacionId");

                    b.Navigation("Afiliado");

                    b.Navigation("Documentacion");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.AfiliadosDomicilios", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Afiliados", "Afiliado")
                        .WithMany()
                        .HasForeignKey("AfiliadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("AfiliadosDomiciliosId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Altura")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Altura");

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<string>("CodigoPostal")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CodigoPostal");

                            b1.Property<string>("Departamento")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Departamento");

                            b1.Property<Guid>("LocalidadesId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LocalidadesId");

                            b1.Property<string>("Piso")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Piso");

                            b1.HasKey("AfiliadosDomiciliosId");

                            b1.HasIndex("LocalidadesId");

                            b1.ToTable("AfiliadosDomicilios", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("AfiliadosDomiciliosId");

                            b1.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Localidades", "Localidad")
                                .WithMany()
                                .HasForeignKey("LocalidadesId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Localidad");
                        });

                    b.Navigation("Afiliado");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.DetalleDocumentacion", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Documentacion", "Documentacion")
                        .WithMany("DetallesDocumentacion")
                        .HasForeignKey("DocumentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Planes", "Plan")
                        .WithMany("DetalleDocumentacion")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documentacion");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Localidades", b =>
                {
                    b.HasOne("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Provincias", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Autorizacion.UsuarioAfiliados", b =>
                {
                    b.Navigation("Afiliados");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Documentacion", b =>
                {
                    b.Navigation("DetallesDocumentacion");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.EstadosCiviles", b =>
                {
                    b.Navigation("Afiliados");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Nacionalidades", b =>
                {
                    b.Navigation("Afiliados");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Parentescos", b =>
                {
                    b.Navigation("Afiliados");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Planes", b =>
                {
                    b.Navigation("Afiliados");

                    b.Navigation("DetalleDocumentacion");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.Provincias", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("OSPeConTI.Afiliaciones.RegistroAfiliaciones.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Afiliados");
                });
#pragma warning restore 612, 618
        }
    }
}
